project_id = "xinpddlavyqkgwnkncst"

[functions.verify-payment]
verify_jwt = true

[functions.match-contacts]
verify_jwt = true

[functions.flutterwave-webhook]
verify_jwt = false

[functions.manage-user-role]
verify_jwt = true

[functions.request-payout]
verify_jwt = true

[functions.scrape-events]
verify_jwt = false
